# title: Mingxuan Li
# author: Mingxuan Li
# email: mingxuan_li@cs.columbia.edu
# description: > # this means to ignore newlines until "show_exerpts:"
  # Hi, this is Mingxuan Li, an active learner and researcher devoted in 
show_excerpts: true # set to true to show excerpts on the homepage
# disqus_shortname: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Mingxuan Li
  tagline: In my end is my beginning.
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  
  navigation:
    # - title: My Work
    #   url: "/my-work"
    - title: CV (Sept. 2022)
      url: "/assets/resume.pdf" 
    - title: Beyond that...
      url: "/"

  email: ml@cs.columbia.edu

  # generate social links in footer
  social_links:
    gscholar: citations?user=V4MEw70AAAAJ
    twitter: Mingxuan0422
    github:  drmeerkat
    linkedIn: in/mingxuan-li
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: plainwhite

google_analytics_key: UA-158807702-1

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
